### ISSUE TITLE
Request for arduino code for glcd128x64

### ISSUE THREAD

**Issue by shehza2002** [cdhigh/lcd12864_st7920_proteus#3]
Aslamo alekum sir
I really appreciate you for your excellent work. Sir i am student right now and i run your proteus examples. Sir i have 2 questions. 1 is why you are not use 8 bit instead of 4bit.
2nd is sir if you shear you arduino based code instead of hex file it is very helpful to understand.
Rana shahzad
Waiting for you response
Shehza2002@gmail.com

**Comment by cdhigh** [comment]
1. Before I developed this model, there was already a model of ST7920 available on the web, but it was not perfect and did not support 4bit and serial communication, so I developed this model to replace it. If you need 8bit operation, there are many examples on the web, just search and got.
2. I use mcu atmega328p but don't use any arduino library, perfer pure C and read/write registers directly, you can compile the demo project in directory '[test](https://github.com/cdhigh/lcd12864_st7920_proteus/tree/main/test)' by Atmel studio v6 or v7.

**Comment by shehza2002** [comment]
Thanks for replay
Sir as you said you have replace it. Please guide me. Or if you have those
examples pleaee shear it. Thanks again
Rana shahzad
