### ISSUE TITLE
Error in simulation

### ISSUE THREAD

**Issue by ColdHorizon-Dev** [cdhigh/lcd12864_st7920_proteus#4]
Hello,
By importing the LCD in proteus, we run a code. shows a problem shown below 

- External model DLL "LCD12864B.DLL" not found. GLE=0x0000007E.
- Simulation FAILED due to fatal simulator errors.

how to work with this?

**Comment by cdhigh** [comment]
Usage:
Copy release/MODELS/LCD12864B.DLL to the MODELS directory of proteus
Copy the files in release/LIBRARY to the LIBRARY directory of proteus
Search 12864B in proteus to find this device

If the erro still persist in, Try to install VC runtime library.
