### ISSUE TITLE
Simulation FAILED due to partition analysis error(s).

### ISSUE THREAD

**Issue by durongze** [cdhigh/lcd12864_st7920_proteus#5]
![image](https://github.com/cdhigh/lcd12864_st7920_proteus/assets/4144559/894ec99d-a2ef-4323-b0f4-b2f1065fc443)

ISIS Release 8.10.03 (Build 29560) (C) Labcenter Electronics 1990- 2020.
Compiling design 'C:\Users\du\Desktop\xxxx\lcd12864_st7920_proteus-main\12864B.pdsprj'.
Netlist compilation completed OK.
Netlist linking completed OK.
Nothing to simulate!
Simulation FAILED due to partition analysis error(s).

**Comment by durongze** [comment]
工程根目录下的12864B.pdsprj 不能用，建议删除。
请使用test/test7920.pdsprj

**Comment by cdhigh** [comment]
用法不一样，工程目录下pdsprj是设计和编译使用的，除非你要修改这个模拟器，否则使用test目录下的pdsprj是正确的

**Comment by durongze** [comment]
哦哦，原来是我没有彻底搞懂。。。。感谢
